### ISSUE TITLE
倒计时结束崩溃

### ISSUE THREAD

**Issue by df13954** [AndroidCoderPeng/DailyTask#13]
```
2022-10-19 17:23:01.289 1972-1972/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pengxh.autodingding, PID: 1972
    java.util.NoSuchElementException
        at java.util.ArrayList$Itr.next(ArrayList.java:863)
        at com.pengxh.autodingding.utils.Utils$1.onFinish(Utils.java:76)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

pixel3 Android11，设置下班打卡倒计时，然后结束崩溃了，没有打开钉钉。

**Comment by AndroidCoderPeng** [comment]
手机未安装钉钉导致，理论上不存在这个问题，已添加保护

**Comment by ff-frida** [comment]
> 理论上不存在这个问题，已添加保护

对了，那个判断钉钉是否安装的方法，我手机上面返回false，但是我手机已经安装了钉钉。
